 
 const CartActionTypes = {
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEM:'ADD_CART_ITEM',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART',
    REMOVE_CART_ITEM:'REMOVE_CART_ITEM',
    CLEAR_CART:'CLEAR_CART'
};


export default CartActionTypes;